# Generated by Django 5.0.3 on 2024-04-04 06:00
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="industry",
            old_name="name",
            new_name="industry_name",
        ),
        migrations.RenameField(
            model_name="position",
            old_name="name",
            new_name="position_name",
        ),
        migrations.RenameField(
            model_name="positiontype",
            old_name="name",
            new_name="position_type_name",
        ),
    ]
