# Generated by Django 5.0.3 on 2024-04-05 13:48
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0002_rename_name_industry_industry_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="positiontype",
            name="position_type_name",
            field=models.CharField(max_length=100),
        ),
    ]
