# Generated by Django 5.0.3 on 2024-05-16 18:17
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0004_alter_positiontype_position_type_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="general",
            options={
                "verbose_name": "Общий опыт",
                "verbose_name_plural": "Общие компетенции",
            },
        ),
        migrations.AlterModelOptions(
            name="industry",
            options={"verbose_name": "Отрасль", "verbose_name_plural": "Отрасли"},
        ),
        migrations.AlterModelOptions(
            name="leader",
            options={
                "verbose_name": "Опыт лидера",
                "verbose_name_plural": "Лидерские компетенции",
            },
        ),
        migrations.AlterModelOptions(
            name="position",
            options={"verbose_name": "Позиция", "verbose_name_plural": "Позиции"},
        ),
        migrations.AlterModelOptions(
            name="positiontype",
            options={
                "verbose_name": "Тип позиции",
                "verbose_name_plural": "Типы позиций",
            },
        ),
        migrations.AlterModelOptions(
            name="profession",
            options={
                "verbose_name": "Профессиональный опыт",
                "verbose_name_plural": "Профессиональные компетенции",
            },
        ),
        migrations.RemoveField(
            model_name="industry",
            name="industry_name",
        ),
        migrations.RemoveField(
            model_name="position",
            name="position_name",
        ),
        migrations.RemoveField(
            model_name="position",
            name="position_type",
        ),
        migrations.RemoveField(
            model_name="positiontype",
            name="position_type_name",
        ),
        migrations.AddField(
            model_name="industry",
            name="name",
            field=models.CharField(
                default=1, max_length=100, unique=True, verbose_name="Название"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="position",
            name="name",
            field=models.CharField(
                db_index=True,
                default=1,
                max_length=100,
                unique=True,
                verbose_name="Название",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="position",
            name="type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="resume.positiontype",
                verbose_name="Тип",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="positiontype",
            name="name",
            field=models.CharField(
                default=1, max_length=100, unique=True, verbose_name="Название"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="general",
            name="general_experience",
            field=models.TextField(unique=True, verbose_name="Опыт"),
        ),
        migrations.AlterField(
            model_name="general",
            name="position_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="resume.positiontype",
                verbose_name="Тип позиции",
            ),
        ),
        migrations.AlterField(
            model_name="leader",
            name="leader_experience",
            field=models.TextField(unique=True, verbose_name="Опыт"),
        ),
        migrations.AlterField(
            model_name="leader",
            name="position_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="resume.positiontype",
                verbose_name="Тип позиции",
            ),
        ),
        migrations.AlterField(
            model_name="positiontype",
            name="is_leader",
            field=models.BooleanField(
                choices=[(True, "Да"), (False, "Нет")], verbose_name="Лидер"
            ),
        ),
        migrations.AlterField(
            model_name="profession",
            name="industry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="resume.industry",
                verbose_name="Отрасль",
            ),
        ),
        migrations.AlterField(
            model_name="profession",
            name="position_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="resume.positiontype",
                verbose_name="Тип позиции",
            ),
        ),
        migrations.AlterField(
            model_name="profession",
            name="professional_experience",
            field=models.TextField(unique=True, verbose_name="Опыт"),
        ),
    ]
